# Generated by Django 5.0.6 on 2024-08-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('product', 'Product'), ('subcategory', 'Subcategory')], default='product', max_length=20),
        ),
    ]
