# Generated by Django 5.0.6 on 2024-08-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_offer_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='products',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='subcategories',
        ),
    ]
