# Generated by Django 5.0.6 on 2024-07-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_product_product_name_alter_productsize_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
