# Generated by Django 5.0.6 on 2024-08-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0001_initial'),
        ('product_app', '0011_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_applied', to='offer_app.offer'),
        ),
    ]
