# Generated by Django 5.0.6 on 2024-08-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_product_applied_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorimage',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
