# Generated by Django 5.0.6 on 2024-08-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(choices=[('purchase', 'Purchase using wallet'), ('return', 'Refund for returned product'), ('cancellation', 'Refund for cancelled order via Razor Pay/Wallet')], max_length=255),
        ),
    ]
