# Generated by Django 5.0.6 on 2024-08-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_alter_wallettransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(choices=[('purchase', 'Purchase using wallet'), ('return', 'Refund for returned product'), ('cancellation', 'Refund for cancelled order via Razor Pay/Wallet'), ('referral', 'Bonus amount for referral')], max_length=255),
        ),
    ]
