# Generated by Django 5.0.6 on 2024-07-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_unique_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
