# Generated by Django 5.0.6 on 2024-07-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_rename_address_type_address_address_title_and_more'),
        ('order_app', '0003_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_line',
            field=models.TextField(default='add'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_title',
            field=models.CharField(default='add', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default='add', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_phone_number',
            field=models.CharField(default='add', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_pin',
            field=models.CharField(default='add', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_post_office',
            field=models.CharField(default='add', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(default='add', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_address', to='account_app.address'),
        ),
    ]
