# Generated by Django 5.0.6 on 2024-07-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_orderitem_return_request_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='return_request_date',
            new_name='return_eligible_day_one',
        ),
    ]
