# Generated by Django 5.0.6 on 2024-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_rename_return_request_date_orderitem_return_eligible_day_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Return Confirmed', 'Return Confirmed'), ('Return Processing', 'Return Processing'), ('Waiting For Pickup', 'Waiting For Pickup'), ('Return Completed', 'Return Completed')], default='Pending', max_length=20),
        ),
    ]
