# Generated by Django 5.0.6 on 2024-07-30 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0002_remove_coupons_max_limit_coupons_description'),
        ('order_app', '0007_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_app.coupons'),
        ),
    ]
