# Generated by Django 5.0.6 on 2024-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Wallet', 'Wallet'), ('RazorPay', 'RazorPay')], max_length=10),
        ),
    ]
