# Generated by Django 5.0.6 on 2024-08-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0012_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
