# Generated by Django 5.0.6 on 2024-08-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0013_order_offer_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer_total',
            new_name='offer_discount_total',
        ),
    ]
