# Generated by Django 5.0.6 on 2024-07-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0003_category_category_image_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_image',
        ),
    ]
