# Generated by Django 5.0.6 on 2024-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0004_remove_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images/'),
        ),
    ]
