# Generated by Django 5.0.6 on 2024-07-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_category_image_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=100),
        ),
    ]
