# Generated by Django 5.0.6 on 2024-07-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0006_alter_subcategory_subcategory_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('subcategory_name', 'category')},
        ),
    ]
