# Generated by Django 5.0.6 on 2024-07-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0007_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_lsited',
            field=models.BooleanField(default=True),
        ),
    ]
