# Generated by Django 5.0.6 on 2024-07-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0008_subcategory_is_lsited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='is_lsited',
            new_name='is_listed',
        ),
    ]
