# Generated by Django 5.0.6 on 2024-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0010_category_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_offer_applied',
            field=models.BooleanField(default=False),
        ),
    ]
