# Generated by Django 5.0.6 on 2024-08-03 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0011_subcategory_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
