# Generated by Django 5.0.6 on 2024-07-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='max_limit',
        ),
        migrations.AddField(
            model_name='coupons',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
