# Generated by Django 5.0.6 on 2024-07-27 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_wishlist'),
        ('product_app', '0008_product_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product_variant')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='size_variant',
        ),
    ]
